name: Android CI with Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version
        id: bump_version
        uses: oflynned/Android-Semantic-Release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_number: ${{ github.run_number }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        env:
          VERSION_CODE: ${{ github.run_number }}
          VERSION_NAME: "0.0.${{ github.run_number }}"
        run: ./gradlew build

      - name: Rename APK
        run: |
          APK_DIR=app/build/outputs/apk/release
          mv "$APK_DIR/app-release.apk" "$APK_DIR/Launchbox-0.0.${{ github.run_number }}.apk"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.version.outputs.filename }}
          path: "app/build/outputs/apk/release/Launchbox-0.0.${{ github.run_number }}.apk"

      - name: Get Changelog
        id: changelog
        shell: bash
        run: |
          changelog="- Initial release"
          if git tag --list | grep .; then
            last_tag=$(git describe --tags --abbrev=0)
            echo "Last tag found: $last_tag"
            changelog=$(git log --pretty=format:'- %s' "$last_tag"..HEAD)
          else
            echo "No tags found — using fallback changelog"
          fi
          printf "changelog<<EOF\n%s\nEOF\n" "$changelog" >> "$GITHUB_ENV"

      - name: Create GitHub Release and Upload APK
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ env.VERSION }}
          body: |
            ${{ github.event.head_commit.message }}
            ## Changelog
            ${{ env.changelog }}
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
