name: Launchbox PR CI

on:
  pull_request:
    branches: [main]

jobs:
  build-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create app directory for keystore
        run: mkdir -p app

      - name: Restore Keystore
        run: |
          mkdir -p app
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/upload-keystore.jks

      - name: Build signed APK with Gradle
        env:
          VERSION_CODE: ${{ github.run_number }}
          VERSION_NAME: "0.0.${{ github.run_number }}"
          KEYSTORE_PATH: ${{ github.workspace }}/app/upload-keystore.jks
        run: ./gradlew build -Pandroid.injected.signing.store.file=$KEYSTORE_PATH -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: List APK files
        run: |
          echo "APK files found:"
          find app/build/outputs/apk/ -iname "*.apk" -exec ls -lh {} \;
